### PR TITLE
Pyright update

### PR DESCRIPTION
**Pull request by agateau-gg**
## Context

This PR syncs pyright configuration to match py-gitguardian:

- update pyright to 1.1.367
- enable the same checks

## What has been done

Mostly simple fixes, but a few trickier changes are in their own commits. In particular IaCScanCollection becomes a generic class (see 2nd commmit).

### CODE REVIEW

**Review by fnareoh — CHANGES_REQUESTED** [review]
Hum something went wrong in the pipeline ? :o

**Comment by agateau-gg** [comment]
> Hum something went wrong in the pipeline ? :o

Yeah, Python 3.8 is getting too old to run latest pyright. Should be better now.

**Review by fnareoh — APPROVED** [review]
Interesting to see the changes surrounding dataclass vs SingleNameSpace I'll remember to avoid them in the future !

**Review by gg-mmill — APPROVED** [review]
Good to me !

**Pull request merged**
