### PR TITLE
chore: ensure no token is present before the test

### PR DESCRIPTION
**Pull request by GG-HH**
Please note that this is a bad fix because the isolated fs is not isolated and this should be fixed.

If I run this test alone with a hmsl_token in my file system, then it fails.

Please note that running the test will delete your current HMSL token if any.

### CODE REVIEW

**Comment by pierrelalanne** [comment]
Not sure to understand the context here @GG-HH ? Was this a failing test before the release process ?
Should we open a separate issue to find a more long term solution for the `isolated_fs` to have the expected behavior?

**Comment by GG-HH** [comment]
Indeed, my description wasn't very explicit (and so is my proposed fix).
If you try to run this test alone while having a HMSL token in your cache, the test will fail because it doesn't use an isolated filesystem and the first assert will fail. I did not take time to investigate why the FS isn't isolated.

**Comment by agateau-gg** [comment]
I think it would be interesting to understand the root cause of the problem here. Where is this cache stored?

**Comment by agateau-gg** [comment]
Ah, I just had a look at the code and I think I know what's happening. It's because the path to the cache file is initialized globally as a Path. I had a similar issue with other parts of the code. A simple fix is to turn `TOKEN_PATH = ...` into a `get_token_path()` function.

**Comment by GG-HH** [comment]
Thank you @agateau-gg , it indeed fixes the issue. I updated my MR.

I also fix a small typo in a docstring.

**Review by agateau-gg — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
