### PR TITLE
Release signed binaries

### PR DESCRIPTION
**Pull request by agateau-gg**
## Context

This PR extends our CI so that signed macOS binaries are built on each release.

## What has been done

Since testing CI code which only triggers on tags is not really possible, I used the following workarounds:

1. The existing sign.yml workflow has been turned into a more generic build_release_assets.yml workflow. This workflow is called by the tag.yml workflow. It can also be called manually.

2. I added a faketag.yml workflow. This is a copy of tag.yml except it triggers on pull requests and does not publish anything: each publish step is replaced by a step listing the downloaded artifacts which would be published. This allow verifies the changes to tag.yml as much as possible. You can see a run of it [here](https://github.com/GitGuardian/ggshield/actions/runs/8629377759).
  This faketag.yml will be removed before merging the PR.

## Review

First commit contains the real work. Second commit just adds faketag.yml and can mostly be ignored (apart from verifying changes made to tag.yml are also present in faketag.yml). I will revert that commit before merging.

### CODE REVIEW

**Review by fnareoh — APPROVED** [review]
Looks good but I"m not sure I understand why you end up with [two macos binaries here](https://github.com/GitGuardian/ggshield/actions/runs/8629377759)  what is "macos-14" ?

**Comment by agateau-gg** [comment]
> Looks good but I"m not sure I understand why you end up with [two macos binaries here](https://github.com/GitGuardian/ggshield/actions/runs/8629377759) what is "macos-14" ?

GitHub terminology is confusing:

- macos-14 is for ARM-based macOS, it uses macOS 14
- macos-latest is for Intel-based macOS

At least that was my understanding until I went back to https://github.com/actions/runner-images, and noticed macos-latest is now the same as macos-14! That changed on [April 2](https://github.com/actions/runner-images/commit/da5ebb36223a06890092a423a0466b28ea2de595.patch).

That's my punishment for not pinning runner versions I guess 😒. Going to pin this runner (and the Ubuntu one).

**Comment by salome-voltz** [comment]
Looks good to me, I'm just not sure to understand how to trigger the Build release assets workflow manually ?

**Review by salome-voltz — APPROVED** [review]

**Comment by agateau-gg** [comment]
> Looks good to me, I'm just not sure to understand how to trigger the Build release assets workflow manually ?

The place to trigger workflows is https://github.com/GitGuardian/ggshield/actions, but there is a trick: you can't trigger it right now because I renamed it, and the workflow must exist in the default branch to be able to trigger it 😞.

Right now you can try to trigger the [sign workflow](https://github.com/GitGuardian/ggshield/actions/workflows/sign.yml), the old name for build_release_assets, which is in default branch.

**Pull request merged**
